---
title: "Activity 19: Internet Safety: Personally Identifiable Information"
subtitle: "Teaching internet safety through the protection of personally identifiable information."
grades: All grades
time_required: "45 minutes"
categories: ["Grade: Kindergarten", "Grade: 1", "Grade: 2", "Grade: 3", "Grade: 4", "Grade: 5", "Grade: 6", "Time: 30 Minutes"]
toc: true 
page-layout: full
---

## Description

In this activity, students will practice internet safety by keeping their digital footprint safe. Students will complete a web module about personally identifiable information and then engage in an activity using robots to create and navigate routes based on potential scam terminology.

## Time Required

- **Estimated Time**: 30-45 minutes

## Materials Required

- [Online Web Module](https://cyber.org/find-curricula/personally-identifiable-information-keys-cybersecurity)
- Wooden blocks
- Papers with PII examples (similar to Activty #8)
- Programmable & Drivable Robot
- IPAD

## Steps to Conduct the Activity

### Difficulty Breakdown

#### Introduction

- Discuss with students about their experiences using the internet and activities they have done online.
- Explain the importance of being able to identify safe and unsafe online communications.
- Play the web module on phishing: [Online Web Module](https://training.knowbe4.com/modstore/view/0654978b-22b8-4b91-808d-af71060a8692)
- After watching, ask students what they learned from the module.

#### Beginner

- Divide students into two groups and provide them with flashcards containing safe and unsafe terms/actions.
- Instruct students to sort the flashcards into safe and unsafe categories. Review the sorted flashcards to ensure understanding before proceeding.
- Using wooden blocks as barriors, have students create a route that their robot can navigate through.
- Allow students to use their robot to navigate through the routes they created.
- Encourage students to create new routes for their robot after completing the initial one.
- 🔍 *Focus Skills*: internet safety, unsafe activity recognition

#### Intermediate

- Divide students into two groups and provide them with flashcards containing safe and unsafe terms/actions.
- Instruct students to sort the flashcards into safe and unsafe categories. Review the sorted flashcards to ensure understanding before proceeding.
- Using wooden blocks and the sorted flashcards, have students create two routes: one for safe terms/actions and one for unsafe terms/actions that their robot can navigate through.
- Allow students to use their robot to navigate through the routes they created.
- Encourage students to create new routes for their robot after completing the initial one.
- 🔍 *Focus Skills*: internet safety, unsafe activity recognition

## Discussion & Reflection

After the activity has been completed, gather the class for a quick debrief. We can ask:

- What did you learn about personally identifiable information?
- What might you do differently online after watching the video?

## Wrap-Up

This activity aims to enhance students' understanding of internet safety by actively engaging them in identifying safe and unsafe sharing of personally identifiable information. By using robots to navigate through created routes, students apply their knowledge in a practical and interactive manner, reinforcing internet safety practices.

## Learning Outcomes

By the end of this activity, students should be able to:

- Understand basic safety practices when using the internet or other online tools.
- Reflect on their previous online usage to establish any necessary changes.
