---
title: "Activity 10: Electrical Currents and LEDs - Arduino"
subtitle: "Enhancing Computational Thinking through Interactive Coding Challenges."
grades: All grades
time_required: "1 hour"
categories: ["Grade: Kindergarten", "Grade: 1", "Grade: 2", "Grade: 3", "Grade: 4", "Grade: 5", "Grade: 6", "Time: 1 Hour"]
toc: true
page-layout: full
---

## Description

In this activity, students will engage in an activity designed to introduce them to the fundamentals of electronics by making a simple circuit. Through levels of increasing difficulty, students will get a hands-on experience that provides them with a foundational understanding of how electronic circuits and programming interact.

## Time Required

- **Estimated Time**: 1 Hour

## Materials required

- Arduino Instructions: [Intro to Basic Electronics with Arduino](https://docs.google.com/document/d/1cPh0NCV_lXEYbUFzkZiseoTPQTM8filLLZxizIvs-Q4/edit#heading=h.h1avinm0cmy6)
- Arduino Board and program
- Arduino USB connector cable
- 3 LEDs
- 3 1k ohm resistor
- Connecting Wire

## Steps to Conduct the Activity

### Introduction
- Acssess insturction in order to run activity.

### Beginner

- Follow the instructions through to the end of the single LED circuits.
- 🔍 *Focus Skills*: creativity, problem-solving, electrical component relationships

### Intermediate

- Follow the instructions through to the end of the single LED circuits.
- For increasing difficulty, continue the activity through the multiple LED circuits.
- 🔍 *Focus Skills*: creativity, problem-solving, electrical component relationships

## Discussion & Reflection

After the activity has been completed, gather the class for a quick debrief. We can ask:

- What did you observe from trying to get the LEDs to light up?
- Relate the activity to everday use of certain electironic that work with simalr electonics like LED lights. 

## Wrap-Up

Introducing students to the fundamentals of electronics equips them with a deeper understanding of how we interact with and manipulate electronic devices. By gaining this foundational knowledge, they can comprehend the essential processes and steps required to make electronic components function effectively. This early exposure not only explains the workings of everyday technology but also fosters curiosity and encourages hands-on experimentation.

## Learning Outcomes

By the end of this activity, students should be able to:

- Understand the function of an LED.
- Build a simple circuit.
- Explore how LEDs interact with other elextrical components.
- Understand the difference between different kinds of circuits.