project:
  type: website
  output-dir: _site

website:
  title: 'Code with Chompers'
  search:
    location: navbar
    type: overlay
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "images/logo.svg"
  navbar:
    left:
      - text: "⚙️ Settings"
        menu:
          - text: "Increase Text Size"
            href: "javascript:increaseTextSize()"
          - text: "Decrease Text Size"
            href: "javascript:decreaseTextSize()"
          - text: "Toggle High Contrast Mode"
            href: "javascript:toggleAccessibilityTheme()"
          - text: "Toggle Dark Mode"
            href: "javascript:toggleTheme()"
          - text: "Reset Settings"
            href: "javascript:resetAccessibilitySettings()"
    right:
      - text: "About"
        href: "about/index.qmd"
      - text: "Outreach Guide"
        href: "technical-leader-guide/index.qmd"
      - text: "All K-6 Activities"
        href: "k-6_activities/index.qmd"
      - text: "Main Modules"
        href: "main_modules/index.qmd"
      - text: "Themed Modules"
        href: "themed-modules/index.qmd"
  page-footer:
    left: '<a href="https://www.cis.allegheny.edu/"><img src="/images/footer_logo.svg" alt="Footer Image" style="height: 70px; vertical-align: middle; margin-right: 5px;"></a>'
    right:
      - icon: github
        href: https://github.com/K-6-computing-literacy/k-6computerliteracywebsite

format:
  html:
    theme: styles.css
    include-in-header: 
      - _includes/settings.html
    highlight-style: github
execute:
  freeze: auto
