project:
  type: website
  output-dir: _site

website:
  title: 'Code with Chompers'
  search:
    location: navbar
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "images/logo.svg"
  navbar:
    right:
      - text: "Outreach Guide"
        href: "technical-leader-guide/index.qmd"
      - text: "Activities"
        href: "activities/index.qmd"
      - text: "About"
        href: "about/index.qmd"
  page-footer:
    left: '<a href="https://www.cis.allegheny.edu/"><img src="/images/footer_logo.png" alt="Footer Image" style="height: 70px; vertical-align: middle; margin-right: 5px;"></a>'
    right:
      - icon: github
        href: https://github.com/K-6-computing-literacy/k-6computerliteracywebsite

format:
  html:
    theme: 
      light: styles.css
      dark: stylesdark.css
    highlight-style: github
execute:
  freeze: auto
