project:
  type: website

website:
  title: 'Code with Chompers'
  search:
    location: navbar
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "images/logonew.png"
  navbar:
    right:
      - text: "Outreach Guide"
        href: "technical-leader-guide/index.qmd"
      - text: "Activities"
        href: "activities/index.qmd"
      - text: "About"
        href: "about/index.qmd"
  page-footer:
    left: '<a href="https://www.cis.allegheny.edu/"><img src="/images/footer_logo.png" alt="Footer Image" style="height: 70px; vertical-align: middle; margin-right: 5px;"></a>'
    right:
      - icon: github
        href: https://github.com/K-6-computing-literacy/k-6computerliteracywebsite

format:
  html:
    mainfont: Inter
    monofont: Roboto
    fontsize: 1.25em
    theme:
      default
    highlight-style: github
    css: css/styles.css

execute:
  freeze: auto
