---
title: "Activity 25: AI & Bias"
subtitle: "Students will learn about underlying themes of bias when training AI and how that impacts us."
grades: All grades
time_required: "45 minutes"
categories: ["Grade: Kindergarten", "Grade: 1", "Grade: 2", "Grade: 3", "Grade: 4", "Grade: 5", "Grade: 6", "Time: 45 Minutes"]
toc: true 
page-layout: full
---

## Description

In this activity, students will learn about how AI can become biased based off of the information used to train it. 

## Time Required

- **Estimated Time**: 30-45 minutes

## Materials Required

- Shared Computer or Projector
- [Lesson Slides Pt.1](https://docs.google.com/presentation/d/1PjqQyi919OfB98pRCJSG95aHLg3OvYIvTBfQE5F3d1E/edit?slide=id.g285acdf149b_0_52#slide=id.g285acdf149b_0_52)
- [Lesson Slides Pt.2](https://docs.google.com/presentation/d/19pTEOpe4gPExaCOp8x91RQERxpmJRPQLMCCVv_tHcnA/edit?slide=id.g24cbe908a3e_0_149#slide=id.g24cbe908a3e_0_149)
- [Trick-or-Treat AI Worksheet](https://docs.google.com/document/d/1XFZyV__BVYx-h16i9vuXz5IzPRdMjoB91vZgLidz8uo/edit?tab=t.0)

## Steps to Conduct the Activity

### Difficulty Breakdown

#### Introduction

- Have all the students group together near the projector.
- Everyone should be able to see and encouraged to respond.

#### Instructions

- Run through the Lesson Slides Pt.1 with the class. Make sure to explain everything the slides cover.
- Run through the Lesson Slides Pt.2 with the class.
About halfway through, the worksheet should be passed out. Completing it is worked in to the slides.
- 🔍 *Focus Skills*: bias understanding, bias reduction, AI literacy

## Discussion & Reflection

After the activity has been completed, gather the class for a quick debrief. We can ask:

- How does AI become biased?
- How does this bias affect you? How might it affect your peers?

## Wrap-Up

This activity aims to enhance students' understanding of AI and potential bias when training it. By looking through examples, students apply their knowledge in a practical and interactive manner, reinforcing their understanding of AI bias.

## Learning Outcomes

By the end of this activity, students should be able to:

- Define AI bias
- Understand how AI bias occurs
- Understand how to help reduce AI bias