name: Quarto CI

on:
  push:
    branches: [main, bug-fixes]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.3.450'

      - name: Install Node.js (for linting tools)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install HTMLHint and Stylelint
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Render Quarto site
        working-directory: computingliteracy
        run: quarto render

      - name: Lint HTML files
        working-directory: computingliteracy
        run: |
          find _site -name "*.html" -print0 | xargs -0 -n1 htmlhint

      - name: Lint CSS files
        working-directory: computingliteracy
        run: |
          find _site -name "*.css" | grep -v site_libs | xargs stylelint
