---
title: "Activity 16: Manual Control and Bulldozing Challenge"
subtitle: "Engaging students in completing challenge cards that utilize the accessory packs and multi-step problem-solving."
grades: 1st–6th
time_required: "30 minutes"
categories: ["Grade: 1", "Grade: 2", "Grade: 3", "Grade: 4", "Grade: 5", "Grade: 6", "Time: 30 Minutes"]
toc: true
page-layout: full
---

## Description

In this activity, students will create and navigate obstacles through block code and the bulldozing attachment. The activity is designed with increasing difficulty based on previous coding experience, allowing students to build their programming logic as they play.

Using Blockly, students will control Dash to move, aim, and push  through obstacles in order to complete challenge cards. Along the way, they'll explore fundamental computer science concepts like sequencing, debugging, conditionals, and loops—all wrapped inside a fun, interactive story.

## Time Required

- **Estimated Time**: 30-45 minutes

## Materials

- Dash Robot (with bulldozer attachment)  
- Small Obstacles (ex: plastic cups, blocks, or small boxes)
- IPAD
- Challenge Cards

## Steps to Conduct the Activity

### Setup

- Split students into small groups. Have them spread out throughout the room, ensuring each group has room to run the activity.
- Each group should recieve one robot, one IPAD, one set of challenge cards, and one set of obstacles.

### Difficulty Breakdown

#### Introduction

- Demonstrate to the students how to attach the bulldoze piece to the Dash robot.
- Give a demonstration of how to drive Dash with this attachment to show the students what they can now do.

### Difficulty Breakdown

#### Beginner
- Set up the first challenge card and run through the challenge using Dash. 
- Start with challenge cards that do not require the use of the bulldozing attachment and work up based on challenge accomplishment.
- 🔍 *Focus Skill*: Following instructions, problem-solving

#### Intermediate
- Set up the first challenge card and run through the challenge using Dash. 
- Start with challenge cards that do not require the use of the bulldozing attachment and work up based on challenge accomplishment.
- Once students have grasped the concept of the bulldoze attachment, allow them to create their own challenges. This is can be with or without the attachment.
- 🔍 *Focus Skill*: Following instructions, problem-solving, creativity

## Discussion & Reflection

After the activity has been completed, gather the class for a quick debrief. We can ask:

- Were there any challenges you found difficult?
- Were you able to complete a challenge first try?
- How many challenges were you able to complete?
- What part did you enjoy the most?

## Wrap-Up

Completing challenges with the use of attachments helps to build foundational programming skills. By adjusting challenge levels and allowing room for imagination, students stay engaged while learning how to think like a programmer: plan, test, adjust, and try again!

## Learning Outcomes

By the end of this activity, students should be able to:

- Understand basic coding principles.
- Utilize robotic attachments.
- Use conditional statements to create decision-making processes in block coding.
- Enhance their computational thinking skills by breaking down a problem into smaller, manageable conditions and actions.
- Test their block code in a practical setup and debug any issues that arise to ensure the robot navigates correctly.
